language: node_js

node_js:
  - v6

services:
  - mysql

addons:
  code_climate:

env:
  NODE_ENV: 'test'

notifications:
  email:
    - alberto@wejs.org

before_script:
  - mysql -e 'create database test;'
